name: Publish Server to Clojars

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: clojars
          server-username: grayskull-dev
          server-password: ${{ secrets.DEPLOY_TOKEN }}
      - name: Store gpg key
        run: echo $GPG_SIGNING_KEY_BASE64 | base64 -d > /tmp/gpg.key
        env:
          GPG_SIGNING_KEY_BASE64: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Build with Maven
        run: ./mvnw -B clean install gpg:sign -Dgpg.signer=bc -Dgpg.keyFilePath=/tmp/gpg.key
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      - name: Deploy modules to Clojars
        run: ./mvnw -B -pl '!simple-app' deploy
